version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DIRECTORY: performance
      MAGIC_STRING: apple
      SCHEDULER_TIME: 1
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"